export const customers = [
  { id: 1, name: 'Rakesh Mishra', location: 'Sawaynchester', orders: 5, spent: 96.14 },
  { id: 2, name: 'Lakshman Singh', location: 'Kaydenville', orders: 12, spent: 22.18 },
  { id: 3, name: 'Dinanath Sah', location: 'East Freidaton', orders: 6, spent: 59.64 },
  { id: 4, name: 'Anmol Yadav', location: 'South Marcellus', orders: 3, spent: 54.52 },
  { id: 5, name: 'Raushan Singh Rajput', location: 'South Olestad', orders: 15, spent: 45.80 },
  { id: 6, name: 'Lokesh Rahul', location: 'Dereckberg', orders: 12, spent: 85.78 },
  { id: 7, name: 'Randhir Kumar', location: 'Franeckview', orders: 5, spent: 128.66 },
  { id: 8, name: 'Khushi Kumari', location: 'Port Kathryne', orders: 7, spent: 113.39 },
  { id: 9, name: 'Pooja Kumari', location: 'McGlynntown', orders: 14, spent: 80.80 },
  { id: 10, name: 'Ruhi Kumari', location: 'Krystalview', orders: 5, spent: 42.03 },
  { id: 11, name: 'Ravi Patel', location: 'Newdale', orders: 10, spent: 78.99 },
  { id: 12, name: 'Sneha Agarwal', location: 'Westwood', orders: 8, spent: 98.45 },
  { id: 13, name: 'Amit Sharma', location: 'Holloway', orders: 4, spent: 65.23 },
  { id: 14, name: 'Priya Mehta', location: 'Lakeville', orders: 9, spent: 110.50 },
  { id: 15, name: 'Vikram Joshi', location: 'Hilltown', orders: 7, spent: 91.75 },
  { id: 16, name: 'Nisha Verma', location: 'Crestview', orders: 6, spent: 58.30 },
  { id: 17, name: 'Saurabh Tiwari', location: 'Brookline', orders: 3, spent: 49.60 },
  { id: 18, name: 'Meena Kumari', location: 'Fairmont', orders: 11, spent: 119.00 },
  { id: 19, name: 'Karan Malhotra', location: 'Elmwood', orders: 2, spent: 33.40 },
  { id: 20, name: 'Divya Rai', location: 'Norwick', orders: 5, spent: 60.00 },
  { id: 21, name: 'Neha Singh', location: 'Lakeside', orders: 8, spent: 105.75 },
  { id: 22, name: 'Gaurav Bansal', location: 'Greenfield', orders: 9, spent: 99.99 },
  { id: 23, name: 'Aarav Kapoor', location: 'Riverview', orders: 10, spent: 120.45 },
  { id: 24, name: 'Anjali Yadav', location: 'Silverlake', orders: 6, spent: 88.88 },
];