export const orders = [
    {
      id: "#12512a",
      date: "May 5, 4:20 PM",
      customer: "Tom Anderson",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 49.90,
    },
    {
      id: "#12523b",
      date: "May 5, 4:15 PM",
      customer: "Jayden Walker",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 34.36,
    },
    {
      id: "#51232c",
      date: "May 5, 4:15 PM",
      customer: "Inez Kim",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 5.51,
    },
    {
      id: "#23534d",
      date: "May 5, 4:12 PM",
      customer: "Francisco Henry",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 29.74,
    },
    {
      id: "#51323e",
      date: "May 5, 4:12 PM",
      customer: "Violet Phillips",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 23.06,
    },
    {
      id: "#35622f",
      date: "May 5, 4:12 PM",
      customer: "Rosetta Becker",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 87.44,
    },
    {
      id: "#34323g",
      date: "May 5, 4:10 PM",
      customer: "Dean Love",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 44.55,
    },
    {
      id: "#56212h",
      date: "May 5, 4:08 PM",
      customer: "Nettie Tyler",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 36.79,
    },
    {
      id: "#76543i",
      date: "May 5, 4:08 PM",
      customer: "Lora Weaver",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 28.78,
    },
    {
      id: "#12512j",
      date: "May 5, 4:05 PM",
      customer: "Vincent Cannon",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 96.46,
    },
    {
      id: "#12345k",
      date: "May 5, 4:05 PM",
      customer: "Nettie Palmer",
      paymentStatus: "Paid",
      orderStatus: "Received",
      total: 25.53,
    },
    {
      id: "#23534l",
      date: "May 5, 4:04 PM",
      customer: "Miguel Harris",
      paymentStatus: "Pending",
      orderStatus: "Ready",
      total: 50.54,
    },
    {
      id: "#12523m",
      date: "May 5, 4:04 PM",
      customer: "Angel Conner",
      paymentStatus: "Pending",
      orderStatus: "Ready",
      total: 63.47,
    },
    {
      id: "#51232n",
      date: "May 5, 4:03 PM",
      customer: "Rosalie Singleton",
      paymentStatus: "Pending",
      orderStatus: "Received",
      total: 91.63,
    },
    {
      id: "#12512o",
      date: "May 5, 4:20 PM",
      customer: "Tom Anderson",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 49.90,
    },
    {
      id: "#12523q",
      date: "May 5, 4:15 PM",
      customer: "Jayden Walker",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 34.36,
    },
    {
      id: "#51232r",
      date: "May 5, 4:15 PM",
      customer: "Inez Kim",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 5.51,
    },
    {
      id: "#23534s",
      date: "May 5, 4:12 PM",
      customer: "Francisco Henry",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 29.74,
    },
    {
      id: "#51323t",
      date: "May 5, 4:12 PM",
      customer: "Violet Phillips",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 23.06,
    },
    {
      id: "#35622u",
      date: "May 5, 4:12 PM",
      customer: "Rosetta Becker",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 87.44,
    },
    {
      id: "#34323v",
      date: "May 5, 4:10 PM",
      customer: "Dean Love",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 44.55,
    },
    {
      id: "#56212w",
      date: "May 5, 4:08 PM",
      customer: "Nettie Tyler",
      paymentStatus: "Paid",
      orderStatus: "Ready",
      total: 36.79,
    },
    {
      id: "#76543x",
      date: "May 5, 4:08 PM",
      customer: "Lora Weaver",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 28.78,
    },
    {
      id: "#12512y",
      date: "May 5, 4:05 PM",
      customer: "Vincent Cannon",
      paymentStatus: "Paid",
      orderStatus: "Shipped",
      total: 96.46,
    },
    {
      id: "#12345z",
      date: "May 5, 4:05 PM",
      customer: "Nettie Palmer",
      paymentStatus: "Paid",
      orderStatus: "Received",
      total: 25.53,
    },
    {
      id: "#23534ab",
      date: "May 5, 4:04 PM",
      customer: "Miguel Harris",
      paymentStatus: "Pending",
      orderStatus: "Ready",
      total: 50.54,
    },
    {
      id: "#12523ac",
      date: "May 5, 4:04 PM",
      customer: "Angel Conner",
      paymentStatus: "Pending",
      orderStatus: "Ready",
      total: 63.47,
    },
    {
      id: "#51232ad",
      date: "May 5, 4:03 PM",
      customer: "Rosalie Singleton",
      paymentStatus: "Pending",
      orderStatus: "Received",
      total: 91.63,
    },
    
  ];
  